version: '3.0'

services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce
    restart: always
    privileged: true
    security-opt:
      - label=disable
    ports:
      - "9000:9000/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - /opt/portainer:/data

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    security-opt:
      - label=disable
    ports:
      - 8123:8123
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

  mqtt:
    container_name: mqtt
    image: "docker.io/eclipse-mosquitto"
    restart: unless-stopped
    security-opt:
      - label=disable
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/mqtt:/mosquitto

  nodered:
    container_name: nodered
    image: "docker.io/nodered/node-red"
    restart: unless-stopped
    security-opt:
      - label=disable
    ports:
      - 1880:1880
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/nodered:/data

  duplicati:
    container_name: duplicati
    image: "lscr.io/linuxserver/duplicati"
    restart: unless-stopped
    security-opt:
      - label=disable
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt:/source

  