version: '3.0'

services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce
    restart: always
    privileged: true
    ports:
      - "9000:9000/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      - /opt/portainer:/data

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

  duplicati:
    container_name: duplicati
    image: "lscr.io/linuxserver/duplicati"
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt:/source