version: '3.0'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: always
    security-opt:
      - label=disable
    ports:
      - 8443:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

  mqtt:
    container_name: mqtt
    image: "docker.io/eclipse-mosquitto"
    restart: always
    security-opt:
      - label=disable
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/mqtt:/mosquitto

  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   image: docker.io/koenkk/zigbee2mqtt
  #   restart: always
  #   security-opt:
  #     - label=disable
  #   volumes:
  #     - /opt/zigbee2mqtt:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     # Frontend port
  #     - 8000:8080
  #   environment:
  #     - TZ=Europe/Copenhagen
  #   devices:
  #     # Make sure this matched your adapter location
  #     - /dev/ttyUSB0:/dev/ttyACM0

  duplicati:
    container_name: duplicati
    image: "lscr.io/linuxserver/duplicati"
    restart: always
    security-opt:
      - label=disable
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt:/source

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: always
    ports:
      - 8082:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/radarr:/config
      - /opt/media:/data
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: always
    ports:
      - 8081:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/sonarr:/config
      - /opt/media:/data
  sabnzbd:
    container_name: sabnzbd
    image: cr.hotio.dev/hotio/sabnzbd:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/sabnzbd:/config
      - /opt/media:/data:rw